[package]
name = "join-sound-johnson"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.2", features = ["mysql", "chrono"] }
chrono = "0.4"
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
poise = { version = "0.5.0", features = ["collector", "cache"]}
songbird = "0.3.0"
[dependencies.serenity]
default-features = false
features = ["voice", "client", "gateway", "model", "cache"]
version = "0.11"
