[package]
name = "join-sound-johnson"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.3", features = ["mysql", "chrono"] }
chrono = "0.4"
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-opentelemetry = "0.23.0"
opentelemetry = "0.22.0"
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"] }
opentelemetry-stdout = { version = "0.3.0", features = ["trace"] }
opentelemetry-otlp = { version = "0.15.0", features = [
  "trace",
  "http-proto",
  "reqwest-client",
] }
poise = { version = "0.5.7", features = ["collector", "cache"] }
songbird = "0.3.2"
regex = "1.10.1"

[dependencies.serenity]
default-features = false
features = ["voice", "client", "gateway", "model", "cache"]
version = "0.11.6"


[lib]
name = "jsj_backend"
path = "src/backend/lib.rs"


[[bin]]
name = "join-sound-johnson"
path = "src/main.rs"
